version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
