app = "ai-portfolio-backend"

[build]
  builder = "Dockerfile"

[env]
  QDRANT_URL = "http://qdrant:6333"
  COLLECTION_NAME = "portfolio"
  MODEL_NAME = "nomic-embed-text"
  UPLOAD_API_KEY = "tu_clave_aqui"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
