app = "ai-portfolio-backend"

[build]
dockerfile = "Dockerfile"

[env]
  QDRANT_URL = "https://qdrant-vector-db.fly.dev"
  COLLECTION_NAME = "portfolio"
  MODEL_NAME = "nomic-embed-text"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[deploy]
  strategy = "immediate"

[experimental]
  auto_rollback = true
